FROM {{ stage3_image }}
MAINTAINER Stefan Junker <code@stefanjunker.de>

RUN echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen && locale-gen
RUN \
  for dir in use mask accept_keywords unmask; do \
    mkdir /etc/portage/package.${dir}; \
    touch /etc/portage/package.${dir}/99auto.conf; \
  done && \
  mkdir /usr/portage && \
  emerge-webrsync {% if portage_date is defined %}--revert={{ portage_date }}{% endif %}

ADD files/make.conf.appendix /tmp/
RUN cat /tmp/make.conf.appendix >> /etc/portage/make.conf

COPY files/portage/bashrc /etc/portage/bashrc

RUN emerge flaggie layman

COPY files/ca-certificates /usr/local/share/ca-certificates/
RUN \
  chmod 644 /usr/local/share/ca-certificates/*.crt && \
  update-ca-certificates

CMD /bin/bash
