FROM {{ stage3_image }}
MAINTAINER Stefan Junker <code@stefanjunker.de>

RUN echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen && locale-gen
RUN mkdir /usr/portage; \
	  emerge-webrsync {% if stage3_date is defined %}--revert={{ stage3_date }}{% endif %} || \
    emerge-webrsync

ADD files/make.conf.appendix /tmp/
RUN cat /tmp/make.conf.appendix >> /etc/portage/make.conf

COPY files/portage/bashrc /etc/portage/bashrc

RUN emerge flaggie layman

COPY files/ca-certificates /usr/local/share/ca-certificates/
RUN \
    chmod 644 /usr/local/share/ca-certificates/*.crt && \
    update-ca-certificates

CMD /bin/bash
