---
#- hosts: all
#  tasks:
#  - name: group by architecture
#    group_by: buildslaves-{{ arch_map[ansible_architecture] }}
#
#- hosts: buildslaves-armv6j_hardfp
#  roles:
#  - { role: docker_buildslave, target_arch: armv6j_hardfp }
#
#- hosts: buildslaves-armv7a_hardfp
#  roles:
#  - { role: docker_buildslave, target_arch: armv7a_hardfp }

- hosts: buildmaster
  vars:
    target_arch: armv6j_hardfp
    target_arch_short: arm
  roles:
  - role: get_stage3
    when: "{{ 'buildslaves-armv6j_hardfp' not in groups }}"
  - role: docker_stage3
    when: "{{ 'buildslaves-armv6j_hardfp' not in groups }}"
  - role: docker_base
    when: "{{ 'buildslaves-armv6j_hardfp' not in groups }}"
#  - role: docker_buildslave 
#    when: "{{ 'buildslaves-armv6j_hardfp' not in groups }}"

#  - { role: docker_buildslave, target_arch: armv7a_hardfp, when: "{{ 'buildslaves-armv7a_hardfp' not in groups }}" }
