---
- hosts: all
  tasks:
  - name: group by architecture
    group_by: key=buildslaves-{{ arch_map[ansible_architecture] }}
    tags: 
      - always
  - name: add buildmaster to groups
    add_host: name={{ groups["buildmaster"][0] }} groups={{ item }}
    when: item not in groups
    with_items:
      - buildslaves-amd64
      - buildslaves-armv6j_hardfp
      - buildslaves-armv7a_hardfp
    tags: 
      - always

- hosts: buildslaves-amd64
  vars:
    target_arch: amd64
    target_arch_short: amd64
  roles:
  - role: docker_buildslave
  - role: docker_buildslave_rootfs

- hosts: buildslaves-armv6j_hardfp
  vars:
    target_arch: armv6j_hardfp
    target_arch_short: arm
  roles:
    - docker_buildslave
    - docker_buildslave_rootfs

- hosts: buildslaves-armv7a_hardfp
  vars:
    target_arch: armv7a_hardfp
    target_arch_short: arm
  roles:
    - docker_buildslave
    - docker_buildslave_rootfs
