FROM {{ base_image }}
MAINTAINER Stefan Junker <code@stefanjunker.de>

RUN \
  {% set package="dev-util/buildbot-slave" %}
  emerge {{ package }} && \
  rm -Rf /usr/portage/distfiles/*

RUN buildslave create-slave {{ buildslave_dir }} {{ hostvars[groups["buildmaster"][0]]["ansible_fqdn"] }} {{ target_arch }} {{ target_arch }}
RUN sed -i -e 's!application.setComponent!#application.setComponent!' {{ buildslave_dir }}/buildbot.tac
RUN chown -R buildbot:buildbot {{ buildslave_dir }}

USER buildbot
CMD twistd --no_save -n --logfile=- --python={{ buildslave_dir }}/buildbot.tac --pidfile={{ buildslave_dir }}/twistd.pid

EXPOSE 9989 8010
