FROM {{ from_image }}
MAINTAINER Stefan Junker <code@stefanjunker.de>

RUN \
  {% set package="dev-util/buildbot-slave" %}
  flaggie {{ package }} +mail +manhole && \
  emerge --autounmask-write=y {{ package }}; \
  etc-update --automode -5 && \
  emerge -u {{ package }} && \
  rm -Rf /usr/portage/distfiles/*

RUN buildslave create-slave {{ buildslave_dir }} {{ master }} {{ name }} {{ passwd }}
RUN sed -i -e 's!application.setComponent!#application.setComponent!' {{ buildslave_dir }}/buildbot.tac
RUN chown -R buildbot:buildbot {{ buildslave_dir }}

USER buildbot
CMD twistd --no_save -n --logfile=- --python={{ buildslave_dir }}/buildbot.tac --pidfile={{ buildslave_dir }}/twistd.pid

EXPOSE 9989 8010
