FROM {{ base_image }}
MAINTAINER Stefan Junker <code@stefanjunker.de>

RUN \
  {% set package="dev-util/buildbot" %}
  flaggie {{ package }} +mail +manhole && \
  emerge --autounmask-write=y {{ package }}; \
  etc-update --automode -5 && \
  emerge -u {{ package }} && \
  rm -Rf /usr/portage/distfiles/*

RUN \
  buildbot create-master {{ buildmaster_dir }} && \
  sed -i -e 's!application.setComponent!#application.setComponent!' {{ buildmaster_dir }}/buildbot.tac && \
  chown -R buildbot:buildbot {{ buildmaster_dir }}

USER buildbot
CMD \
  wget {{ buildmaster_config_url }} -O {{ buildmaster_dir }}/master.cfg && \
  [ ! -e {{ buildmaster_dir }}/twistd.pid ] || rm {{ buildmaster_dir }}/twistd.pid && \
  twistd --no_save -n --logfile=- --python={{ buildmaster_dir }}/buildbot.tac --pidfile={{ buildmaster_dir }}/twistd.pid

EXPOSE 9989 8010
