---
- name: Add official docker apt repository
  apt_repository: repo='deb https://get.docker.com/ubuntu docker main' state=present
- name: Add key for docker ppa
  apt_key: keyserver=keyserver.ubuntu.com id=36A1D7869245C8950F966E92D8576A8BA88D21E9 state=present

- name: Add apt repository for docker-py
  apt_repository: repo='deb http://ppa.launchpad.net/opencontrail/ppa/ubuntu trusty main'
- name: Add key for opencontrail ppa
  apt_key: keyserver=keyserver.ubuntu.com id=F04D4FBCA09579F7599A2A3716BD83506839FE77 state=present

- name: Install python-apt
  apt:
    pkg: "{{ item }}"
    state: installed
    update_cache: yes
  with_items:
    - python-apt
    - apt-transport-https

- name: Install buildserver dependencies on apt-based distributions
  apt:
    pkg: "{{ item }}"
    state: installed
  with_items:
    - lxc-docker
    - python-docker-py
