---
- include: apt.yml
  when: ansible_pkg_mgr == "apt"
    
- include: portage.yml
  when: ansible_pkg_mgr == "portage"

- name: add user to the docker group
  user: >
      name={{ ansible_ssh_user }}
      append=yes
      groups=docker
  register: add_user_to_docker_group

- name: Run docker service
  service:
    name: docker
    enabled: yes
    state: started
