---
- include: apt.yml
  when: ansible_pkg_mgr == "apt"
    
- include: portage.yml
  when: ansible_pkg_mgr == "portage"

- name: add user to the docker group
  user: >
      name={{ ansible_ssh_user }}
      append=yes
      groups=docker

- name: Run docker service
  service:
    name: docker
    enabled: yes
    state: started

- name: Disable apparmor for docker
  shell: aa-complain /etc/apparmor.d/docker
  when: apparmor_installed.rc == 0
