---
- include: apt.yml
  when: ansible_pkg_mgr == "apt"
    
- include: portage.yml
  when: ansible_pkg_mgr == "portage"

- name: Run docker service
  service:
    name: docker
    enabled: yes
    state: started
