---
name: buildslave_rootfs
arch: "{{ native_arch }}.{{ target_arch}}"

docker_containername: "{{ name }}_{{ arch }}"
role_dir: "{{ playbook_dir }}/roles/docker_{{ name }}"
dockerfile_dir: "{{ base_dir }}/{{ arch }}/docker_{{ name }}"
buildslave_dir: /var/lib/buildslave
docker_ports: ["0"]
docker_volumes: 
   - "/var/run/docker.sock:/var/run/docker.sock"
docker_privileged: yes
sudo_pwless_commands:
  - "/usr/bin/docker"
  - "/usr/bin/qemu-*"
  - "/bin/tar"
  - "/bin/mount"
  - "/usr/bin/proot"
  - "/sbin/btrfs"
  - "/sbin/mkfs.btrfs"
  - "/bin/mknod"
