---
name: buildslave_rootfs
arch: "{{ native_arch }}.{{ target_arch}}"

docker_containername: "{{ name }}_{{ arch }}"
role_dir: "{{ playbook_dir }}/roles/docker_{{ name }}"
dockerfile_dir: "{{ base_dir }}/{{ arch }}/docker_{{ name }}"
buildslave_dir: /var/lib/buildslave
docker_ports: ["0"]
docker_volumes: 
   - "/var/run/docker.sock:/var/run/docker.sock"
   - "/var/lib/docker:/var/lib/docker"
   - "/usr/portage:/host-portage:ro"
   - "/backup"
docker_privileged: yes
sudo_pwless_commands:
  - "/bin/mount */rootfs.btrfs.img */rootfs.btrfs.mnt"
  - "/bin/umount */rootfs.btrfs.*"
  - "/sbin/btrfs subvolume create */rootfs.btrfs.mnt/*"
  - "/sbin/btrfs subvolume delete */rootfs.btrfs.mnt/*"
  - "/sbin/btrfs subvolume snapshot */rootfs.btrfs.mnt/*"
  - "/sbin/btrfs filesystem balance */rootfs.btrfs.mnt/*"
  - "/usr/bin/proot */rootfs.btrfs.mnt/qemu_prepare/*"
  - "/usr/bin/docker images -q embedux/stage3-*"
  - "/usr/bin/docker save *"
  - "/usr/bin/crossdev"
  - "/bin/tar */rootfs.btrfs.mnt/*"
