FROM {{ base_image }}
MAINTAINER Stefan Junker <code@stefanjunker.de>

RUN \
  {% set package="dev-util/buildbot-slave" %}
  emerge {{ package }} && \
  rm -Rf /usr/portage/distfiles/*

RUN \
   buildslave create-slave {{ buildslave_dir }} {{
   hostvars[groups["buildmaster"][0]]["ansible_fqdn"] }} rootfs_{{ target_arch }} {{ buildbot_psk }} && \
  chown -R buildbot:buildbot {{ buildslave_dir }} && \
  sed -i -e 's!application.setComponent!#application.setComponent!' {{ buildslave_dir }}/buildbot.tac

RUN \
  {% set package="app-admin/ansible" %}
  {% set flags="+kw::~"+native_arch_short %}
  flaggie {{ package }} {{ flags }}  && \
  emerge --autounmask-write=y {{ package }}; \
  etc-update --automode -5 && \
  emerge -u {{ package }} && \
  rm -Rf /usr/portage/distfiles/*


RUN \
  {% set kernel_version=ansible_kernel.split('.')[0]+"."+ansible_kernel.split('.')[1] %}
#  {% set package="=sys-kernel/gentoo-sources-"+kernel_version+"*" %}
  {% set package="sys-kernel/gentoo-sources" %}
  {% set flags="+use::experimental +kw::~"+native_arch_short %}
  flaggie {{ package }} {{ flags }}  && \
  emerge --autounmask-write=y {{ package }}; \
  etc-update --automode -5 && \
  emerge -u {{ package }} && \
  rm -Rf /usr/portage/distfiles/*
  
ADD files/kernel.config /usr/src/linux/.config

RUN \
  {% set package="app-emulation/docker" %}
  {% set flags="+kw::~"+native_arch_short %}
  flaggie {{ package }} {{ flags }}  && \
  emerge --autounmask-write=y {{ package }}; \
  etc-update --automode -5 && \
  emerge -u {{ package }} && \
  rm -Rf /usr/portage/distfiles/*

RUN \
  {% set package="=sys-apps/proot-4*" %}
  {% set flags="+kw::~"+native_arch_short %}
  flaggie {{ package }} {{ flags }}  && \
  emerge --autounmask-write=y {{ package }}; \
  etc-update --automode -5 && \
  emerge -u {{ package }} && \
  rm -Rf /usr/portage/distfiles/*

RUN \
  {% set package="sys-fs/btrfs-progs" %}
  {% set flags="+kw::~"+native_arch_short %}
  flaggie {{ package }} {{ flags }}  && \
  emerge --autounmask-write=y {{ package }}; \
  etc-update --automode -5 && \
  emerge -u {{ package }} && \
  rm -Rf /usr/portage/distfiles/*

RUN \
  {% set package="app-admin/sudo" %}
  {% set flags="-use::sendmail" %}
  flaggie {{ package }} {{ flags }}  && \
  emerge --autounmask-write=y {{ package }}; \
  etc-update --automode -5 && \
  emerge -u {{ package }} && \
  rm -Rf /usr/portage/distfiles/* && \
  usermod -a -G wheel buildbot && \
  echo %wheel ALL=NOPASSWD: {{ sudo_pwless_commands|join(',') }} >> /etc/sudoers

RUN \
  mkdir {{ embedux_tmp }}/download -p && \
  chown buildbot:buildbot -R {{ embedux_tmp }} && \
  mkdir /home/buildbot && \
  chown buildbot:buildbot /home/buildbot && \
  usermod -d /home/buildbot buildbot

RUN \
  {% set package="app-emulation/qemu" %}
  {% set flags="+qemu_user_targets_"+target_arch_short+" +qemu_softmmu_targets_"+target_arch_short+" -opengl -gtk +static-user +virtfs +xattr" %}
  flaggie {{ package }} {{ flags }}  && \
  emerge --autounmask-write=y {{ package }}; \
  etc-update --automode -5 && \
  emerge -u {{ package }} && \
  rm -Rf /usr/portage/distfiles/*

{% if native_arch != target_arch %}
RUN \
  {% set package="sys-devel/distcc" %}
  {% set flags="-use::sendmail" %}
  flaggie {{ package }} {{ flags }}  && \
  emerge --autounmask-write=y {{ package }}; \
  etc-update --automode -5 && \
  emerge -u {{ package }} && \
  rm -Rf /usr/portage/distfiles/* && \

RUN \
  {% set package="sys-devel/crossdev" %}
  emerge --autounmask-write=y {{ package }}; \
  etc-update --automode -5 && \
  emerge -u {{ package }} && \
  mkdir -p /usr/local/portage/{metadata,profiles} && \
  echo 'local-overlay' > /usr/local/portage/profiles/repo_name && \
  echo 'masters = gentoo' > /usr/local/portage/metadata/layout.conf && \
  chown -R portage:portage /usr/local/portage && \
  echo 'PORTDIR_OVERLAY="/usr/local/portage ${PORTDIR_OVERLAY}"' >> /etc/portage/make.conf && \
  rm -Rf /usr/portage/distfiles/* 
{% endif %}


ENV EMBEDUX_TMP {{ embedux_tmp }}
ENV NATIVE_ARCH {{ native_arch }}
ENV NATIVE_ARCH_SHORT {{ native_arch_short }}
ENV TARGET_ARCH {{ target_arch }}
ENV TARGET_ARCH_SHORT {{ target_arch_short }}

USER buildbot
CMD \
  [ ! -e {{ buildslave_dir }}/twistd.pid ] || rm {{ buildslave_dir }}/twistd.pid && \
  twistd --no_save -n --logfile=- --python={{ buildslave_dir }}/buildbot.tac --pidfile={{ buildslave_dir }}/twistd.pid
