
post_src_unpack() {
    if [[ $(type -t epatch_user) == function ]]; then
        if pushd -- "$S" 2>&3; then
            epatch_user
            popd 2>&3
        else
            epatch_user
        fi 3>/dev/null
    fi
}
