---
- name: run container
  docker: >
    image={{ docker_image }}
    ports={{ docker_ports|join(",") }}
    volumes={{ docker_volumes|join(",") }}
    state={{ state|default("running") }}
  tags:
    - run
