---
- name: manage existing container
  docker: >
    image={{ docker_image }}
    name={{ docker_imagename }}_{{ target_arch }}
    ports={{ docker_ports|join(",") }}
    volumes={{ docker_volumes|join(",") }}
    state={{ docker_state|default("running") }}
  tags:
    - run
