---
- name: Set generic image fact
  set_fact: >
    docker_imagename={{ docker_image_prefix }}/{{ name }}-{{ arch }}:{{ stage3_date }}
  tags:
    - always

- name: Set specific named image fact
  set_fact: >
    {{ name }}_image={{ docker_imagename }}
  tags:
    - always
