---
- include_vars: main.yml
  tags:
    - always

- include: ../../common/tasks/prepare_directory.yml
- include: ../../common/tasks/render_templates.yml
- name: render make.conf.appendix
  local_action:
    module: template
    src: make.conf.appendix.j2
    dest: "{{ role_dir }}/files/make.conf.appendix"
  tags:
    - generate

- include: ../../common/tasks/sync_dir.yml
- include: ../../common/tasks/docker_image_present.yml
- include: ../../common/tasks/set_facts.yml
